In [22]:
import pandas as pd
import csv

nov = pd.read_csv("allresults_nov7.csv", encoding='latin-1')
nov

,path,pagetitle,pageid,wordcount,Keep,snippet
0,corgiresults.json,"b""101 Dalmatians II: Patch's London Adventure""",1730084,2022,f,"b'strong, brave, and faithful <span class=""sea..."
1,germanshepresults.json,"b""101 Dalmatians II: Patch's London Adventure""",1730084,2022,f,"b'starry-eyed, naive ways to become a strong, ..."
2,goldenretresults.json,"b""2002\xe2\x80\x9303 St. Francis Terriers men'...",43361186,157,f,"b'Center\xc2\xa0(425) Hackensack, NJ January 1..."
3,goldenretresults.json,"b""2007\xe2\x80\x9308 Georgetown Hoyas men's ba...",14518554,4858,f,b'County (UMBC) in the first round. The Hoyas ...
4,bulldogresults.json,"b""2011\xe2\x80\x9312 Butler Bulldogs men's bas...",29627686,1382,f,"b'The 2011\xe2\x80\x9312 Butler <span class=""s..."
5,goldenretresults.json,"b""2012\xe2\x80\x9313 Canisius Golden Griffins ...",37437244,106,f,"b'Canisius <span class=""searchmatch"">Golden</s..."
6,goldenretresults.json,"b""2013\xe2\x80\x9314 Vermont Catamounts men's ...",40746354,116,f,"b'Center\xc2\xa0(1,116) Bangor, ME 01/18/2014 ..."
7,goldenretresults.json,"b""2014 Wake Forest Demon Deacons men's soccer ...",42218306,325,f,b'Ranking indicates NCAA Tournament seeding. W...
8,pomeranianresults.json,"b""2015 Kids' Choice Awards""",42375597,956,f,b'Sheppard Lorde Jamie McDell Iggy Azalea Grum...
9,goldenretresults.json,"b""2015\xe2\x80\x9316 NCAA Division I men's bas...",45711414,6550,f,"b'but places the <span class=""searchmatch"">Gol..."
10,bulldogresults.json,"b""2017 AFL Women's Rising Star""",53112908,253,f,"b'Gaskin, Lee; Navaratnam, Dinny (7 February 2..."
11,goldenretresults.json,"b""2017\xe2\x80\x9318 NCAA Division I men's bas...",53405125,8421,f,"b'Events Center, replacing Fleisher Center. UM..."
12,goldenretresults.json,"b""2017\xe2\x80\x9318 NCAA Division I women's b...",54548244,5221,f,"b'Events Center, replacing Fleisher Center. UM..."
13,bulldogresults.json,"b""2018 AFL Women's Rising Star""",56467988,244,f,"b'au. Retrieved 6 February 2018. Buxton, Aaron..."
14,aussieresults.json,"b""2018 AFL Women's season""",55619637,1345,f,b'possession stops the football being touched ...
15,bulldogresults.json,"b""2018 AFL Women's season""",55619637,1345,f,"b'televised matches (three), Adelaide, Brisban..."
16,shihresults.json,"b""2019 AFC U-16 Women's Championship qualifica...",57538179,2543,f,b'Jiayu Li Lanlan Wang Minhui Wang Siqian Wang...
17,germanshepresults.json,"b""30 millions d'amis""",53255029,998,f,b'owned by Jean-Pierre Hutin and his wife Reha...
18,aussieresults.json,"b""A Dog's Purpose (film)""",48359710,2510,t,b'veterinarian\'s office. Bailey reincarnates ...
19,corgiresults.json,"b""A Dog's Purpose (film)""",48359710,2510,t,b'shot by the kidnapper. Reborn again in the m...
20,germanshepresults.json,"b""A Dog's Purpose (film)""",48359710,2510,t,b'veterinarian\'s office. Bailey reincarnates ...
21,germanshepresults.json,"b""A Dog's Purpose""",35739004,1164,t,b' where he is once again put down. Bailey wak...
22,goldenretresults.json,"b""A Dog's Purpose""",35739004,1164,t,"b'including Toby, are subsequently euthanized...."
23,aussieresults.json,"b""Adam Ant's musical career""",38788784,11663,f,"b'the 1984 Montreux Pop Festival, where they g..."
24,boxerresults.json,"b""Adam Ant's musical career""",38788784,11663,f,"b'in keeping with the album title, Ant undress..."
25,germanshepresults.json,"b""Adam Ant's musical career""",38788784,11663,f,"b'the 1984 Montreux Pop Festival, where they g..."
26,germanshepresults.json,"b""Aesop's Fables""",240755,12092,f,b'Fabulae Aesopi carmine elegiaco redditae in ...
27,aussieresults.json,"b""Agatha Christie's Poirot""",170661,1095,f,b'Affair at the Victory Ball (1991) Miss Batte...
28,bulldogresults.json,"b""Ain't She Tweet""",18557182,625,f,"b'deliveryman and rushes into the yard, only t..."
29,boxerresults.json,"b""Allan's Illustrated Edition of Tyneside Song...",35861384,668,f,b'Cullercoats Fish-Lass \xe2\x80\x93 (The) Edw...
...,...,...,...,...,...,...
15385,bulldogresults.json,b'Zachery Kouwe',26249881,1437,NaN,b'Promoted to Director at Dukas Public Relatio...
15386,bulldogresults.json,b'Zack & Quack',43833604,234,NaN,b'2012\xe2\x80\x9313) Franklin (1997\xe2\x80\x...
15387,shibaresults.json,b'Zack Follett',21147537,492,NaN,b'Follett. He graduated with a major in Americ...
15388,aussieresults.json,b'Zane Grey',205593,5725,NaN,"b'unspoiled lands, particularly the islands of..."
15389,labresults.json,b'Zanjeer (dog)',2078354,386,NaN,b'Persian) (7 January 1992 - 16 November 2000)...
15390,shihresults.json,b'Zawisza Czarny (ship)',2457607,174,NaN,b'Mikhail Kutuzov\xe2\x9a\x93 (1954) Nautilus\...
15391,boxerresults.json,b'Zayn Malik',46230076,5562,NaN,b'One Direction\'s Zayn&quot;. &quot;One Direc...
15392,germanshepresults.json,b'Zduha\xc4\x87',11716814,10264,NaN,b'individual domestic animal could also be reg...
15393,beagleresults.json,b'Zell Miller',335066,3402,NaN,"b'that <span class=""searchmatch"">dog</span> wo..."
15394,shihresults.json,b'Zen scriptures',35868209,6579,NaN,b'make a display of verbal expressions [pu-<sp...
15395,bichonresults.json,b'Zentarr Elizabeth',35049816,780,NaN,b'going forward to the final. She qualified fo...
15396,pomeranianresults.json,b'Zentarr Elizabeth',35049816,780,NaN,"b'Zentarr Elizabeth (2005\xe2\x80\x932017), al..."
15397,poodleresults.json,b'Zentarr Elizabeth',35049816,780,NaN,b'Breed and went on to place reserve in the Ut...
15398,poodleresults.json,b'Zerene eurydice',522944,278,NaN,b'\'dogface\' name comes from a wing pattern r...
15399,shihresults.json,b'Zhenren',15730095,5507,NaN,"b'Chuang <span class=""searchmatch"">Tzu</span>...."
15400,shihresults.json,b'Zhenren',15730095,5507,NaN,"b'Chuang <span class=""searchmatch"">Tzu</span>...."
15401,shihresults.json,b'Zhuang Zhou',166152,1938,NaN,"b'\xcb\x88d\xca\x92o\xca\x8a/), often known as..."
15402,shihresults.json,b'Zhuansun Shi',44404315,446,NaN,b'TranscriptionsStandard MandarinHanyu Pinyin ...
15403,chihuahuaresults.json,b'Zilla (TriStar Godzilla)',1338891,2948,NaN,b'monsters. It was also featured in advertisem...
15404,shihresults.json,b'Ziying',767690,456,f,b'Ziying (died January 206 \xe2\x80\x89BC) was...
15405,shihresults.json,b'Zodiac (schooner)',5706541,1081,f,b'Mikhail Kutuzov\xe2\x9a\x93 (1954) Nautilus\...
15406,bulldogresults.json,b'Zoey 101',1487450,1779,f,b'(2014\xe2\x80\x9318) 100 Things to Do Before...
15407,goldenretresults.json,b'Zoom! The Best of 1995\xe2\x80\x932016',52192308,251,f,"b'&quot;Play It Cool&quot; (single mix, origin..."
15408,germanshepresults.json,b'Zsa Zsa Gabor',152860,3864,f,b'was held on December 30 in a Catholic ceremo...
15409,bichonresults.json,b'Zuchon',45383349,805,f,"b'Shichon is a hybrid breed <span class=""searc..."
15410,shihresults.json,b'Zuchon',45383349,805,f,b'hybrid breed dog or a designer dog. It is cr...
15411,shihresults.json,b'Zuchon',45383349,805,f,"b'Shichon is a hybrid breed <span class=""searc..."
15412,shihresults.json,b'Zuowang',36980498,7041,f,"b'Herbert Allen, tr. (1926), Chuang <span clas..."
15413,germanshepresults.json,b'Zuyaqui',47065423,160,t,"b'Mexican <span class=""searchmatch"">dog</span>..."
15414,bulldogresults.json,b'Zynga',21955841,8908,f,b'July 2007. Zynga was named after Pincus\' Am...

In [23]:
true_nov = nov[ nov["Keep"] == "t" ]

In [24]:
wiki_pages = true_nov.groupby("path")['pageid'].count()
wiki_pages = wiki_pages.to_frame().reset_index()

In [25]:
wiki_pages

                            path  pageid
0             aussieresults.json       3
1             beagleresults.json      19
2             bichonresults.json       2
3              boxerresults.json       2
4           brusselsresults.json       1
5            bulldogresults.json       6
6          chihuahuaresults.json      12
7      cockerspanielresults.json       3
8              corgiresults.json       6
9           dobermanresults.json       4
10   englishspringerresults.json       4
11        germanshepresults.json      15
12         goldenretresults.json      17
13               labresults.json      10
14          papillonresults.json       1
15         pekingeseresults.json       3
16        pomeranianresults.json       2
17            poodleresults.json       8
18               pugresults.json       6
19             shibaresults.json       5
20              shihresults.json       5
21           sibhuskresults.json       3
22           wirefoxresults.json       1
23  yorkshireterrierresults.json       1

In [26]:
wiki_count = true_nov.groupby("path")['wordcount'].sum()
wiki_count
wiki_count = wiki_count.to_frame().reset_index()

In [27]:
final_combo = pd.read_excel("FilteredDog_Dataset_Combined.xlsx")
final_combo

,Ranked Number (AKC),Breed Name,Breed Class (AKC),PuppyBowl_Number Contestants (Last 5 Years),Westminster (all time),KnowYourMeme,Wiki_Path
0,1,Retriever (Labrador),Sporting,11,0,1,labresults.json
1,2,German Shepherd Dogs,Herding/Guardian,4,2,0,germanshepresults.json
2,3,Retrievers (Golden),Sporting,1,0,2,goldenretresults.json
3,5,Bulldogs,Non-sporting,2,2,0,bulldogresults.json
4,6,Beagles,Hound,3,2,0,beagleresults.json
5,7,Poodles,Standard/Miniature/Toy,5,9,0,poodleresults.json
6,9,Yorkshire Terriers,Toy,3,1,0,yorkshireterrierresults.json
7,11,Boxers,Working,4,4,1,boxerresults.json
8,12,Siberian Huskies,Working,1,1,0,sibhuskresults.json
9,15,Pembroke Welsh Corgis,Herding,3,0,0,corgiresults.json
10,16,Doberman Pinschers,Working,1,4,0,dobermanresults.json
11,17,Australian Shepherds,Herding,6,0,1,aussieresults.json
12,20,Shih Tzu,Toy,7,0,0,shihresults.json
13,22,Pomeranians,Toy,4,1,0,pomeranianresults.json
14,27,Spaniels (English Springer),Sporting,1,6,0,englishspringerresults.json
15,29,Spaniels (Cocker),Sporting,3,4,0,cockerspanielresults.json
16,31,Pugs,Toy,3,1,0,pugresults.json
17,32,Chihuahuas,Toy,8,0,1,chihuahuaresults.json
18,45,Shiba Inu,Non-sporting,1,0,3,shibaresults.json
19,46,Bichons Frises,Non-sporting,0,2,1,bichonresults.json
20,53,Papillons,Toy,1,1,0,papillonresults.json
21,88,Pekingese,Toy,1,4,0,pekingeseresults.json
22,94,Brussels Griffons,Toy,2,0,0,brusselsresults.json
23,99,Fox Terriers (Wire),Terrier,2,14,0,wirefoxresults.json

In [28]:
df_merge1 = pd.merge(final_combo, wiki_pages, how = "left", left_on = "Wiki_Path", right_on = "path")
df_merge1

,Ranked Number (AKC),Breed Name,Breed Class (AKC),PuppyBowl_Number Contestants (Last 5 Years),Westminster (all time),KnowYourMeme,Wiki_Path,path,pageid
0,1,Retriever (Labrador),Sporting,11,0,1,labresults.json,labresults.json,10
1,2,German Shepherd Dogs,Herding/Guardian,4,2,0,germanshepresults.json,germanshepresults.json,15
2,3,Retrievers (Golden),Sporting,1,0,2,goldenretresults.json,goldenretresults.json,17
3,5,Bulldogs,Non-sporting,2,2,0,bulldogresults.json,bulldogresults.json,6
4,6,Beagles,Hound,3,2,0,beagleresults.json,beagleresults.json,19
5,7,Poodles,Standard/Miniature/Toy,5,9,0,poodleresults.json,poodleresults.json,8
6,9,Yorkshire Terriers,Toy,3,1,0,yorkshireterrierresults.json,yorkshireterrierresults.json,1
7,11,Boxers,Working,4,4,1,boxerresults.json,boxerresults.json,2
8,12,Siberian Huskies,Working,1,1,0,sibhuskresults.json,sibhuskresults.json,3
9,15,Pembroke Welsh Corgis,Herding,3,0,0,corgiresults.json,corgiresults.json,6
10,16,Doberman Pinschers,Working,1,4,0,dobermanresults.json,dobermanresults.json,4
11,17,Australian Shepherds,Herding,6,0,1,aussieresults.json,aussieresults.json,3
12,20,Shih Tzu,Toy,7,0,0,shihresults.json,shihresults.json,5
13,22,Pomeranians,Toy,4,1,0,pomeranianresults.json,pomeranianresults.json,2
14,27,Spaniels (English Springer),Sporting,1,6,0,englishspringerresults.json,englishspringerresults.json,4
15,29,Spaniels (Cocker),Sporting,3,4,0,cockerspanielresults.json,cockerspanielresults.json,3
16,31,Pugs,Toy,3,1,0,pugresults.json,pugresults.json,6
17,32,Chihuahuas,Toy,8,0,1,chihuahuaresults.json,chihuahuaresults.json,12
18,45,Shiba Inu,Non-sporting,1,0,3,shibaresults.json,shibaresults.json,5
19,46,Bichons Frises,Non-sporting,0,2,1,bichonresults.json,bichonresults.json,2
20,53,Papillons,Toy,1,1,0,papillonresults.json,papillonresults.json,1
21,88,Pekingese,Toy,1,4,0,pekingeseresults.json,pekingeseresults.json,3
22,94,Brussels Griffons,Toy,2,0,0,brusselsresults.json,brusselsresults.json,1
23,99,Fox Terriers (Wire),Terrier,2,14,0,wirefoxresults.json,wirefoxresults.json,1

In [29]:
df_merge2 = pd.merge(df_merge1, wiki_count, how = "left", left_on = "Wiki_Path", right_on = "path")
df_merge2

,Ranked Number (AKC),Breed Name,Breed Class (AKC),PuppyBowl_Number Contestants (Last 5 Years),Westminster (all time),KnowYourMeme,Wiki_Path,path_x,pageid,path_y,wordcount
0,1,Retriever (Labrador),Sporting,11,0,1,labresults.json,labresults.json,10,labresults.json,8834
1,2,German Shepherd Dogs,Herding/Guardian,4,2,0,germanshepresults.json,germanshepresults.json,15,germanshepresults.json,16449
2,3,Retrievers (Golden),Sporting,1,0,2,goldenretresults.json,goldenretresults.json,17,goldenretresults.json,22060
3,5,Bulldogs,Non-sporting,2,2,0,bulldogresults.json,bulldogresults.json,6,bulldogresults.json,5067
4,6,Beagles,Hound,3,2,0,beagleresults.json,beagleresults.json,19,beagleresults.json,48701
5,7,Poodles,Standard/Miniature/Toy,5,9,0,poodleresults.json,poodleresults.json,8,poodleresults.json,13167
6,9,Yorkshire Terriers,Toy,3,1,0,yorkshireterrierresults.json,yorkshireterrierresults.json,1,yorkshireterrierresults.json,5480
7,11,Boxers,Working,4,4,1,boxerresults.json,boxerresults.json,2,boxerresults.json,5079
8,12,Siberian Huskies,Working,1,1,0,sibhuskresults.json,sibhuskresults.json,3,sibhuskresults.json,4782
9,15,Pembroke Welsh Corgis,Herding,3,0,0,corgiresults.json,corgiresults.json,6,corgiresults.json,9678
10,16,Doberman Pinschers,Working,1,4,0,dobermanresults.json,dobermanresults.json,4,dobermanresults.json,3491
11,17,Australian Shepherds,Herding,6,0,1,aussieresults.json,aussieresults.json,3,aussieresults.json,8126
12,20,Shih Tzu,Toy,7,0,0,shihresults.json,shihresults.json,5,shihresults.json,8981
13,22,Pomeranians,Toy,4,1,0,pomeranianresults.json,pomeranianresults.json,2,pomeranianresults.json,3287
14,27,Spaniels (English Springer),Sporting,1,6,0,englishspringerresults.json,englishspringerresults.json,4,englishspringerresults.json,4421
15,29,Spaniels (Cocker),Sporting,3,4,0,cockerspanielresults.json,cockerspanielresults.json,3,cockerspanielresults.json,4115
16,31,Pugs,Toy,3,1,0,pugresults.json,pugresults.json,6,pugresults.json,6772
17,32,Chihuahuas,Toy,8,0,1,chihuahuaresults.json,chihuahuaresults.json,12,chihuahuaresults.json,11562
18,45,Shiba Inu,Non-sporting,1,0,3,shibaresults.json,shibaresults.json,5,shibaresults.json,9271
19,46,Bichons Frises,Non-sporting,0,2,1,bichonresults.json,bichonresults.json,2,bichonresults.json,3627
20,53,Papillons,Toy,1,1,0,papillonresults.json,papillonresults.json,1,papillonresults.json,1632
21,88,Pekingese,Toy,1,4,0,pekingeseresults.json,pekingeseresults.json,3,pekingeseresults.json,3442
22,94,Brussels Griffons,Toy,2,0,0,brusselsresults.json,brusselsresults.json,1,brusselsresults.json,997
23,99,Fox Terriers (Wire),Terrier,2,14,0,wirefoxresults.json,wirefoxresults.json,1,wirefoxresults.json,1961

In [30]:
df_merge2.drop(["path_x", "path_y"], axis = 1, inplace = True)

In [31]:
df_merge2

,Ranked Number (AKC),Breed Name,Breed Class (AKC),PuppyBowl_Number Contestants (Last 5 Years),Westminster (all time),KnowYourMeme,Wiki_Path,pageid,wordcount
0,1,Retriever (Labrador),Sporting,11,0,1,labresults.json,10,8834
1,2,German Shepherd Dogs,Herding/Guardian,4,2,0,germanshepresults.json,15,16449
2,3,Retrievers (Golden),Sporting,1,0,2,goldenretresults.json,17,22060
3,5,Bulldogs,Non-sporting,2,2,0,bulldogresults.json,6,5067
4,6,Beagles,Hound,3,2,0,beagleresults.json,19,48701
5,7,Poodles,Standard/Miniature/Toy,5,9,0,poodleresults.json,8,13167
6,9,Yorkshire Terriers,Toy,3,1,0,yorkshireterrierresults.json,1,5480
7,11,Boxers,Working,4,4,1,boxerresults.json,2,5079
8,12,Siberian Huskies,Working,1,1,0,sibhuskresults.json,3,4782
9,15,Pembroke Welsh Corgis,Herding,3,0,0,corgiresults.json,6,9678
10,16,Doberman Pinschers,Working,1,4,0,dobermanresults.json,4,3491
11,17,Australian Shepherds,Herding,6,0,1,aussieresults.json,3,8126
12,20,Shih Tzu,Toy,7,0,0,shihresults.json,5,8981
13,22,Pomeranians,Toy,4,1,0,pomeranianresults.json,2,3287
14,27,Spaniels (English Springer),Sporting,1,6,0,englishspringerresults.json,4,4421
15,29,Spaniels (Cocker),Sporting,3,4,0,cockerspanielresults.json,3,4115
16,31,Pugs,Toy,3,1,0,pugresults.json,6,6772
17,32,Chihuahuas,Toy,8,0,1,chihuahuaresults.json,12,11562
18,45,Shiba Inu,Non-sporting,1,0,3,shibaresults.json,5,9271
19,46,Bichons Frises,Non-sporting,0,2,1,bichonresults.json,2,3627
20,53,Papillons,Toy,1,1,0,papillonresults.json,1,1632
21,88,Pekingese,Toy,1,4,0,pekingeseresults.json,3,3442
22,94,Brussels Griffons,Toy,2,0,0,brusselsresults.json,1,997
23,99,Fox Terriers (Wire),Terrier,2,14,0,wirefoxresults.json,1,1961

In [32]:
final_dataset = df_merge2.rename( columns = {'pageid': 'Wiki_Num_Page', 'wordcount': 'Wiki_Wordcount'})
final_dataset

,Ranked Number (AKC),Breed Name,Breed Class (AKC),PuppyBowl_Number Contestants (Last 5 Years),Westminster (all time),KnowYourMeme,Wiki_Path,Wiki_Num_Page,Wiki_Wordcount
0,1,Retriever (Labrador),Sporting,11,0,1,labresults.json,10,8834
1,2,German Shepherd Dogs,Herding/Guardian,4,2,0,germanshepresults.json,15,16449
2,3,Retrievers (Golden),Sporting,1,0,2,goldenretresults.json,17,22060
3,5,Bulldogs,Non-sporting,2,2,0,bulldogresults.json,6,5067
4,6,Beagles,Hound,3,2,0,beagleresults.json,19,48701
5,7,Poodles,Standard/Miniature/Toy,5,9,0,poodleresults.json,8,13167
6,9,Yorkshire Terriers,Toy,3,1,0,yorkshireterrierresults.json,1,5480
7,11,Boxers,Working,4,4,1,boxerresults.json,2,5079
8,12,Siberian Huskies,Working,1,1,0,sibhuskresults.json,3,4782
9,15,Pembroke Welsh Corgis,Herding,3,0,0,corgiresults.json,6,9678
10,16,Doberman Pinschers,Working,1,4,0,dobermanresults.json,4,3491
11,17,Australian Shepherds,Herding,6,0,1,aussieresults.json,3,8126
12,20,Shih Tzu,Toy,7,0,0,shihresults.json,5,8981
13,22,Pomeranians,Toy,4,1,0,pomeranianresults.json,2,3287
14,27,Spaniels (English Springer),Sporting,1,6,0,englishspringerresults.json,4,4421
15,29,Spaniels (Cocker),Sporting,3,4,0,cockerspanielresults.json,3,4115
16,31,Pugs,Toy,3,1,0,pugresults.json,6,6772
17,32,Chihuahuas,Toy,8,0,1,chihuahuaresults.json,12,11562
18,45,Shiba Inu,Non-sporting,1,0,3,shibaresults.json,5,9271
19,46,Bichons Frises,Non-sporting,0,2,1,bichonresults.json,2,3627
20,53,Papillons,Toy,1,1,0,papillonresults.json,1,1632
21,88,Pekingese,Toy,1,4,0,pekingeseresults.json,3,3442
22,94,Brussels Griffons,Toy,2,0,0,brusselsresults.json,1,997
23,99,Fox Terriers (Wire),Terrier,2,14,0,wirefoxresults.json,1,1961

In [33]:
outfile = "final_dog_dataset.csv"
final_dataset.to_csv(outfile)