In [1]:
import pandas as pd
import csv

final = pd.read_csv("final_dog_dataset.csv")
final

,Ranked Number (AKC),Breed Name,Breed Class (AKC),PuppyBowl_Number Contestants (Last 5 Years),Westminster (all time),KnowYourMeme,Wiki_Path,Wiki_Num_Page,Wiki_Wordcount
0,1,Retriever (Labrador),Sporting,11,0,1,labresults.json,10,8834
1,2,German Shepherd Dogs,Herding/Guardian,4,2,0,germanshepresults.json,15,16449
2,3,Retrievers (Golden),Sporting,1,0,2,goldenretresults.json,17,22060
3,5,Bulldogs,Non-sporting,2,2,0,bulldogresults.json,6,5067
4,6,Beagles,Hound,3,2,0,beagleresults.json,19,48701
5,7,Poodles,Standard/Miniature/Toy,5,9,0,poodleresults.json,8,13167
6,9,Yorkshire Terriers,Toy,3,1,0,yorkshireterrierresults.json,1,5480
7,11,Boxers,Working,4,4,1,boxerresults.json,2,5079
8,12,Siberian Huskies,Working,1,1,0,sibhuskresults.json,3,4782
9,15,Pembroke Welsh Corgis,Herding,3,0,0,corgiresults.json,6,9678
10,16,Doberman Pinschers,Working,1,4,0,dobermanresults.json,4,3491
11,17,Australian Shepherds,Herding,6,0,1,aussieresults.json,3,8126
12,20,Shih Tzu,Toy,7,0,0,shihresults.json,5,8981
13,22,Pomeranians,Toy,4,1,0,pomeranianresults.json,2,3287
14,27,Spaniels (English Springer),Sporting,1,6,0,englishspringerresults.json,4,4421
15,29,Spaniels (Cocker),Sporting,3,4,0,cockerspanielresults.json,3,4115
16,31,Pugs,Toy,3,1,0,pugresults.json,6,6772
17,32,Chihuahuas,Toy,8,0,1,chihuahuaresults.json,12,11562
18,45,Shiba Inu,Non-sporting,1,0,3,shibaresults.json,5,9271
19,46,Bichons Frises,Non-sporting,0,2,1,bichonresults.json,2,3627
20,53,Papillons,Toy,1,1,0,papillonresults.json,1,1632
21,88,Pekingese,Toy,1,4,0,pekingeseresults.json,3,3442
22,94,Brussels Griffons,Toy,2,0,0,brusselsresults.json,1,997
23,99,Fox Terriers (Wire),Terrier,2,14,0,wirefoxresults.json,1,1961

In [3]:
breed_class = final.groupby("Breed Class (AKC)")['Breed Name'].count()
breed_class

Breed Class (AKC)
Herding                   2
Herding/Guardian          1
Hound                     1
Non-sporting              3
Sporting                  4
Standard/Miniature/Toy    1
Terrier                   1
Toy                       8
Working                   3
Name: Breed Name, dtype: int64

In [4]:
class_per_page = final.groupby("Breed Class (AKC)")['Wiki_Num_Page'].sum()
class_per_page

Breed Class (AKC)
Herding                    9
Herding/Guardian          15
Hound                     19
Non-sporting              13
Sporting                  34
Standard/Miniature/Toy     8
Terrier                    1
Toy                       31
Working                    9
Name: Wiki_Num_Page, dtype: int64

In [ ]:
import matplotlib as pyplot